### ISSUE TITLE
echo_dec

### ISSUE THREAD

**Issue by faruqamar** [ktekeli/audio-steganography-algorithms#1]
Hi, I'm Faruq, I just tried your code, the code really awesome, I want to ask, is it possible to use your code in the encrypted file such the enrypted file from docx file that I've encrypted first? I tried echo data hiding in single kernel btw.
Thank You

**Comment by ktekeli** [comment]
Hello @faruqamar, I didn't understand your question clearly. Do you mean "hiding docx files into audios"  or "hiding encrypted text into audios" with this technique"?

Though the answer is "yes" for both questions. You can embed anything in binary format. But, echo hiding is very limited in terms of embedding capacity. If you use an audio signal sampled at 44.1 kHz, using 8000 samples for one bit, and having 1 kb of data to hide, you need an audio clip around 25 minutes long. If you are going to use wav files, I would suggest you to use LSB method.

**Comment by faruqamar** [comment]
yes for both, I use flac audio sampled at 96 kHz 32 bit, is it still possible for hiding encrypted file or docx file  and the size about 600 kb into audios using echo data hiding?

**Comment by ktekeli** [comment]
@faruqamar You can use this method while hiding encrypted text. But consider that you may need to change character decoding type (conversion of retrieved bit sequence) since your encryption method may have special characters. However, you will have problem with the size of file while hiding 600 kb of data if you use this method in your case.  You would need 600*25 minutes long audio clip.

As I mentioned above, I guess "least significant bit coding" will suit your problem better if you are working with audio codecs that have lossless compression such as WAV and FLAC.

**Comment by faruqamar** [comment]
well since I have essay about hiding encrypted text (docx) into flac audio using echo hiding, and I only have few minutes for the audio, probably I should change the docx file data into txt, thank you very much sir for your code and your answer, have a nice day sir :)

**Comment by ktekeli** [comment]
@faruqamar I am glad to hear that this repository was helpful for you. Good luck in your essay. I am closing this issue on github.
