### ISSUE TITLE
Implement Quantization index modulation using CNV.

### ISSUE THREAD

**Issue by vishal-wadhwa** [ktekeli/audio-steganography-algorithms#2]

**Comment by ktekeli** [comment]
Hello @vishal-wadhwa I didn't understand anything about this issue. Could you clarify it?

**Comment by vishal-wadhwa** [comment]
Hi!

Sorry for this really unclear issue. 
Actually I am working on a project that requires an implementation of QIM (using complementary neighbour vertices) but I cannot find it anywhere. 

Could not find any algorithm or resources to implement it.

There is a research paper on it but it does not offer an implementation in terms of, like, how to implement it a language or what part of codec would it be.

And, since yours is the only repository that mentions QIM so I was hoping you could provide a little insight on how to go about implementing it or if you've an algorithm, could you please add it to this repository? 😅😅

**Comment by ktekeli** [comment]
I was planning to write rest of algorithms that I have mentioned in my to-do list, but I have focused on transformation domain approaches later on. QIM is very similar to LSB coding, but I didn't have time to write a clear algorithm for it.

I do not think you can find any implementation of such a specific algorithm online, because people do not share source codes related to audio steganography. 

Good luck in your project!

**Comment by vishal-wadhwa** [comment]
Thank you so much for your response. :)
And yeah, people haven't shared even the barebones algo about anything related to QIM or some other audio steganography algo.

Kudos to you, you've atleast shared some of them.

**Comment by ktekeli** [comment]
I will surely share the basic approach of QIM here when I have free time to continue to write. And you are welcome to contribute to this repository if you write it before I do. 

I plan to share rest of my work related to transformation domains as well, but I see that this repository is used without any citation to the original source. So I am not sure about that for now.

Best regards
